### PR TITLE
Wmsautoscaling

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by gjn** [comment]
Zappa is what we needed.

This is pretty neat!

**Comment by gjn** [comment]
aehm. so no more aws lambda?

**Comment by gjn** [comment]
ping @loicgasser

**Comment by loicgasser** [comment]
we're trying different approaches there is still a branch called lambda

**Comment by loicgasser** [comment]
The idea is to put it directly on the wms autoscaled instance. This could be an excellent option for us.
No external traffic, autoscaled and probably much faster overall.

**Comment by loicgasser** [comment]
We would use lambda to optimize the images on PUT event. Which could already be used for current mapproxy solution and any bucket we put non-optimized tiles.

**Comment by gjn** [comment]
One (or two) less component(s) / hops might make it faster, indeed. So it's good to test all options.

I'd rather have the WMS in AWS Lambda than this proxy in the WMS Autoscaling group ;=)

**Comment by gjn** [comment]
Great idea on the image optimisation. That's exactly what Lambda is for.

**Comment by loicgasser** [comment]
the code change is minor, we'll have both in parallel to test

**Comment by gjn** [comment]
perfect!

**Pull request merged**
