### PR TITLE
Add gutter support

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by gjn** [comment]
If I understand correctly, the gutter can be specified in the WMTS request, right?

So something like: `https://wmts105.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/21781/19/34/60.jpeg?gutter=10`
?

**Comment by loicgasser** [comment]
yes, this is temporary though. We can't ask other people to add a gutter parameter in a WMTS request.
I don't think it's possible directly in mapserver without impacting perfs too much as this is a global option at the moment.

**Comment by loicgasser** [comment]
test here http://codepen.io/loicgasser/pen/oZKaKb?editors=0010

**Comment by gjn** [comment]
Copy that. In worst case, could be fixed number in this service (would be applied to all requests).

**Pull request merged**
